name: Publish Logseq graph
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 使用官方 Action 导出网页，更稳定，不会有404问题
      - name: Build Logseq SPA
        uses: logseq/publish-spa@v0.3.0
        with:
          graph-directory: .
          output-directory: public

      - name: Add .nojekyll
        run: touch public/.nojekyll

      # 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
